In [38]:
import pandas as pd
import numpy as np

In [39]:
df= pd.read_csv("spam.csv",encoding='ISO-8859-1')

In [40]:
df=df.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1)

In [41]:
df

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [42]:
df=df.rename(columns={'v1':'target','v2':'text'})

In [43]:
df

     target                                               text
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham              Will Ì_ b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [44]:
df['target'].dtype

dtype('O')

In [46]:
df['target'] = df['target'].replace({'ham':0, 'spam':1})
df['target'] = df['target'].astype(int)

C:\Users\Muhammad Ali\AppData\Local\Temp\ipykernel_22228\4142178858.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['target'] = df['target'].replace({'ham':0, 'spam':1})

In [52]:
df.duplicated().sum()

np.int64(403)

In [55]:
df=df.drop_duplicates(keep='first')

In [56]:
df.duplicated().sum()

np.int64(0)

In [58]:
df.shape

(5169, 2)

In [62]:
df['target'].value_counts()

target
0    4516
1     653
Name: count, dtype: int64

In [64]:
pip install nltk

Collecting nltk
  Downloading nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: click in C:\Users\Muhammad Ali\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in C:\Users\Muhammad Ali\AppData\Local\Programs\Python\Python313\Lib\site-packages (from nltk) (1.5.3)
Collecting regex>=2021.8.3 (from nltk)
  Downloading regex-2026.5.9-cp313-cp313-win_amd64.whl.metadata (41 kB)
Collecting tqdm (from nltk)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: colorama in C:\Users\Muhammad Ali\AppData\Local\Programs\Python\Python313\Lib\site-packages (from click->nltk) (0.4.6)
Downloading nltk-3.9.4-py3-none-any.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   --------------------------- ------------ 1.0/1.6 MB 3.2 MB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 2.8 MB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 2.8 MB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 2.8 MB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 2.8 MB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 2.8 MB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 2.8 MB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 2.8 MB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 2.8 MB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 551.7 kB/s  0:00:02
Downloading regex-2026.5.9-cp313-cp313-win_amd64.whl (277 kB)
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, regex, nltk

   ---------------------------------------- 0/3 [tqdm]
   ---------------------------------------- 0/3 [tqdm]
   ---------------------------------------- 0/3 [tqdm]
   ------------- -------------------------- 1/3 [regex]
   ------------- -------------------------- 1/3 [regex]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   -------------------------- ------------- 2/3 [nltk]
   ---------------------------------------- 3/3 [nltk]

Successfully installed nltk-3.9.4 regex-2026.5.9 tqdm-4.67.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [93]:
import nltk

In [94]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to C:\Users\Muhammad
[nltk_data]     Ali\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [67]:
df['num_characters']=df['text'].apply(len)

C:\Users\Muhammad Ali\AppData\Local\Temp\ipykernel_22228\399031894.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['num_characters']=df['text'].apply(len)

In [68]:
df

,target,text,num_characters
0,0,"Go until jurong point, crazy.. Available only ...",111
1,0,Ok lar... Joking wif u oni...,29
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,155
3,0,U dun say so early hor... U c already then say...,49
4,0,"Nah I don't think he goes to usf, he lives aro...",61
...,...,...,...
5567,1,This is the 2nd time we have tried 2 contact u...,161
5568,0,Will Ì_ b going to esplanade fr home?,37
5569,0,"Pity, * was in mood for that. So...any other s...",57
5570,0,The guy did some bitching but I acted like i'd...,125
5571,0,Rofl. Its true to its name,26

In [86]:
df['num_words']=df['text'].apply(lambda x:len(nltk.word_tokenize(x)))

C:\Users\Muhammad Ali\AppData\Local\Temp\ipykernel_22228\1118471538.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['num_words']=df['text'].apply(lambda x:len(nltk.word_tokenize(x)))

In [87]:
df

,target,text,num_characters,num_words,num_sentence
0,0,"Go until jurong point, crazy.. Available only ...",111,24,2
1,0,Ok lar... Joking wif u oni...,29,8,2
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,155,37,2
3,0,U dun say so early hor... U c already then say...,49,13,1
4,0,"Nah I don't think he goes to usf, he lives aro...",61,15,1
...,...,...,...,...,...
5567,1,This is the 2nd time we have tried 2 contact u...,161,35,4
5568,0,Will Ì_ b going to esplanade fr home?,37,9,1
5569,0,"Pity, * was in mood for that. So...any other s...",57,15,2
5570,0,The guy did some bitching but I acted like i'd...,125,27,1
5571,0,Rofl. Its true to its name,26,7,2

In [88]:
df['num_sentence']=df['text'].apply(lambda x:len(nltk.sent_tokenize(x)))

C:\Users\Muhammad Ali\AppData\Local\Temp\ipykernel_22228\3985788005.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['num_sentence']=df['text'].apply(lambda x:len(nltk.sent_tokenize(x)))

In [89]:
df

,target,text,num_characters,num_words,num_sentence
0,0,"Go until jurong point, crazy.. Available only ...",111,24,2
1,0,Ok lar... Joking wif u oni...,29,8,2
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,155,37,2
3,0,U dun say so early hor... U c already then say...,49,13,1
4,0,"Nah I don't think he goes to usf, he lives aro...",61,15,1
...,...,...,...,...,...
5567,1,This is the 2nd time we have tried 2 contact u...,161,35,4
5568,0,Will Ì_ b going to esplanade fr home?,37,9,1
5569,0,"Pity, * was in mood for that. So...any other s...",57,15,2
5570,0,The guy did some bitching but I acted like i'd...,125,27,1
5571,0,Rofl. Its true to its name,26,7,2

In [103]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Muhammad
[nltk_data]     Ali\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [108]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
import string
from nltk.corpus import stopwords

In [111]:
def text_transform(text):
    text=text.lower()
    text=nltk.word_tokenize(text)

    y=[]
    for i in text:
        if i.isalnum():
            y.append(i)

    text=y[:]
    y.clear()
    for i in text:
        if i not in stopwords.words('english') and i not in string.punctuation:
            y.append(i) 

    text=y[:]
    y.clear()

    for i in text:
        y.append(ps.stem(i))

    return " ".join(y)

In [112]:
text_transform('Hello how are you doing i am doing just fine and today i am going to the covert and i am going be dancing so very much and enjoy soooo much')

'hello fine today go covert go danc much enjoy soooo much'

In [113]:
df['transformed_text']=df['text'].apply(text_transform)

C:\Users\Muhammad Ali\AppData\Local\Temp\ipykernel_22228\225956876.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['transformed_text']=df['text'].apply(text_transform)

In [115]:
df.head()

,target,text,num_characters,num_words,num_sentence,transformed_text
0,0,"Go until jurong point, crazy.. Available only ...",111,24,2,go jurong point crazi avail bugi n great world...
1,0,Ok lar... Joking wif u oni...,29,8,2,ok lar joke wif u oni
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,155,37,2,free entri 2 wkli comp win fa cup final tkt 21...
3,0,U dun say so early hor... U c already then say...,49,13,1,u dun say earli hor u c alreadi say
4,0,"Nah I don't think he goes to usf, he lives aro...",61,15,1,nah think goe usf live around though

In [116]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer

In [155]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
X_train_scale=scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)

In [124]:
from sklearn.model_selection import train_test_split

In [127]:
y=df['target'].values

In [128]:
X_test,X_train,y_test,y_train=train_test_split(X,y,test_size=0.2,random_state=2)

In [137]:
cv=CountVectorizer()
tf=TfidfVectorizer(max_features=2000)

In [138]:
X=tf.fit_transform(df['transformed_text']).toarray()

In [139]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,classification_report

In [140]:
gnb=GaussianNB()
np=MultinomialNB()
be=BernoulliNB()

In [141]:
gnb.fit(X_train,y_train)
y_pred=gnb.predict(X_test)
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(precision_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.91      0.93      3620
           1       0.53      0.75      0.62       515

    accuracy                           0.89      4135
   macro avg       0.75      0.83      0.78      4135
weighted avg       0.91      0.89      0.89      4135

0.8856106408706167
0.5289256198347108

In [142]:
np.fit(X_train,y_train)
y_pred=np.predict(X_test)
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(precision_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.90      1.00      0.95      3620
           1       1.00      0.21      0.34       515

    accuracy                           0.90      4135
   macro avg       0.95      0.60      0.65      4135
weighted avg       0.91      0.90      0.87      4135

0.9013301088270859
1.0

In [143]:
be.fit(X_train,y_train)
y_pred=be.predict(X_test)
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(precision_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.88      1.00      0.94      3620
           1       0.91      0.04      0.08       515

    accuracy                           0.88      4135
   macro avg       0.90      0.52      0.51      4135
weighted avg       0.88      0.88      0.83      4135

0.8800483675937122
0.9130434782608695

In [149]:
from sklearn.neighbors import KNeighborsClassifier

In [151]:
kn=KNeighborsClassifier()

In [144]:
from sklearn.ensemble import RandomForestClassifier

In [147]:
rt=RandomForestClassifier(n_estimators=100,random_state=2)

In [148]:
rt.fit(X_train,y_train)
y_pred=rt.predict(X_test)
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(precision_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      1.00      0.97      3620
           1       1.00      0.58      0.73       515

    accuracy                           0.95      4135
   macro avg       0.97      0.79      0.85      4135
weighted avg       0.95      0.95      0.94      4135

0.9475211608222491
0.9966666666666667

In [154]:

kn.fit(X_train,y_train)
y_pred=kn.predict(X_test)
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(precision_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.94      1.00      0.97      3620
           1       0.97      0.56      0.71       515

    accuracy                           0.94      4135
   macro avg       0.96      0.78      0.84      4135
weighted avg       0.94      0.94      0.94      4135

0.9429262394195889
0.9696969696969697

In [156]:
from sklearn.svm import SVC

In [157]:
sv=SVC()

In [159]:
sv.fit(X_train_scale,y_train)
y_pred=sv.predict(X_test_scale)
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(precision_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      0.99      0.96      3620
           1       0.89      0.43      0.58       515

    accuracy                           0.92      4135
   macro avg       0.91      0.71      0.77      4135
weighted avg       0.92      0.92      0.91      4135

0.9230955259975816
0.8924302788844621

In [160]:
pip install pickle

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement pickle (from versions: none)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for pickle

In [161]:
import pickle

In [165]:
pickle.dump(np, open("model.pkl", "wb"))
pickle.dump(tf, open("vectorizer.pkl", "wb"))